app_id         = "demo-serverless"
app_env        = "dev"
region         = "us-east-1"
aws_profile    = "DVA-C01"
repo_url       = "https://github.com/Yoimer/training-tf-lambda-api"
lambda_package = "../function.zip"